const constants = {
  GET_TODOS: "GET_TODOS",
  ADD_TODO: "ADD_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  UPDATE_TODOS: "UPDATE_TODOS",
  DELETE_TODO: "DELETE_TODO",
  SET_COMPLETED: "SET_COMPLETED",
  SET_COMPLETED_ALL: "SET_COMPLETED_ALL",
  SET_PAGE: "SET_PAGE",
  SET_OFFSET: "SET_OFFSET",
  SET_COUNT: "SET_COUNT",
  SET_ERROR: "SET_ERROR",
  SET_FILTER: "SET_FILTER",
  TODOS_AT_PAGE: 5,
};

export default constants;
